name: netpinproc.server.dev
on:
  push:    
    branches: [ netpinproc.server.build ]  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        VERSION: 1.0.0.7-dev-3
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x

      - name: Dotnet Publish NetpinProc.Server
        run: |
            dotnet publish "Tools\NetPinProc.Game.Server\Server\NetPinProc.Game.Manager.Server.csproj" -c Release -o netpinproc.server
            7z a -tzip "NetPinProc.Server-win-${VERSION}.zip" "netpinproc.server" # add pingod addons

      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
             token: ${{ secrets.GITHUB_TOKEN }}        
             generateReleaseNotes: false    
             replacesArtifacts: true
             prerelease: true # Pre release dev flag
             allowUpdates: true # allow the release files to be updated and not create a new release every time
             tag: ${{ github.ref_name }} # branch or tag name
             # include exported windows game zip and source project zip
             artifacts: "*.zip"