name: netpinproc.server.webapp
on:
  push:    
    tags: [server-v*]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        VERSION: 1.0.0.20
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 7.0.x

      - name: Dotnet Publish NetpinProc.Server.Linux
        run: |
            dotnet publish "Tools\NetPinProc.Game.Server\Server\NetPinProc.Game.Manager.Server.csproj" -c Release -o netpinproc.server.linux
            7z a -tzip "NetPinProc.Server-linux-${VERSION}.zip" "netpinproc.server.linux"

      - name: Dotnet Publish NetpinProc.Server.Win
        run: |
            dotnet publish "Tools\NetPinProc.Game.Server\Server\NetPinProc.Game.Manager.Server.csproj" -r win-x64 -c Release -o netpinproc.server.win
            7z a -tzip "NetPinProc.Server-win-${VERSION}.zip" "netpinproc.server.win"

      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
             token: ${{ secrets.GITHUB_TOKEN }}        
             generateReleaseNotes: false    
             replacesArtifacts: true
             prerelease: false # Pre release dev flag
             allowUpdates: true # allow the release files to be updated and not create a new release every time
             makeLatest: true
             #tag: ${{ github.ref_name }} # branch or tag name
             name: "NetPinProc.Server Builds" # Use a fixed name and upload the artifacts to it
             # include exported windows game zip and source project zip
             artifacts: "*.zip"